### PR TITLE
added bbox selection support for spatial queries

### PR DESCRIPTION
**Pull request by cambierr**

### CODE REVIEW

**Comment by daschl** [comment]
Hi @cambierr , thanks for your pull request! Actually bbox was removed on purpose and the ranges are preferred now. If you want to read more on this, check out https://github.com/couchbase/geocouch/wiki/Spatial-Views-API#queries :)

**Comment by cambierr** [comment]
Okay I understand but because of that the SDK does not works on spatial queries, at least  in CB server 3.x.x

So what about CB 4.x.x ?

Sent from a mobile device. Excuse brevety and typos.

Le 2 juil. 2015 11:45, Michael Nitschinger <notifications@github.com> a écrit :

Hi @cambierr<https://github.com/cambierr> , thanks for your pull request! Actually bbox was removed on purpose and the ranges are preferred now. If you want to read more on this, check out https://github.com/couchbase/geocouch/wiki/Spatial-Views-API#queries :)

-

**Comment by daschl** [comment]
@cambierr the 2.x SDK spatial view api should be compatible with 3.0x, but not with 2.x server. 4.x will also work properly.. can you show me the query which is not working?

Also @vmx will help us figure it out.

**Comment by cambierr** [comment]
Here is a post with details:
https://forums.couchbase.com/t/errors-when-using-2-1-3-sdk-for-spatial-views-in-box-selection/4370

**Comment by daschl** [comment]
@cambierr okay cool, let's follow up there then

**Comment by daschl** [comment]
closing this out since I think the discussion has been on the forums.

**Pull request closed without merging**
