### PR TITLE
JsonObject: Check if 'name' is null for put() methods. This check sho…

### PR DESCRIPTION
**Pull request by ShreyasAdPushup**
…uld prevent TranscodingException later when updating/inserting the JsonDocument to the database. It will also prevent exception while calling JsonObject.toString() and help debug issues rather quickly.

### CODE REVIEW

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

To get this change in and collaborate in code review, please register on Gerrit and accept our CLA.  More detailed instructions are available here: http://developer.couchbase.com/open-source-projects#how-to-contribute-code.

Note: Please contact us if you have any issues registering with Gerrit!  If you are not registered after 7 days, the Pull Request will automatically be closed.

::SDKBOT/PR:no_cla

**Comment by daschl** [comment]
@simonbasle how do you think we should proceed on this?

**Comment by simonbasle** [comment]
@daschl: user hasn't signed the CLA (according to bot) and didn't answer to the last comments I made... @ShreyasAdPushup are you available to follow up on it?

**Comment by daschl** [comment]
I'll close this due to inactivity, please reopen if you still have issues!

**Pull request closed without merging**
