### PR TITLE
feat: add support to ANY AND EVERY expression.

### PR DESCRIPTION
**Pull request by uribro**
Adding support to create ANY AND EVERY expression.

### CODE REVIEW

**Comment by daschl** [comment]
@uribro hi, thanks for your contribution! We are actually using gerrit, and everything is detailed in here: https://github.com/couchbase/couchbase-java-client/blob/master/CONTRIBUTING.md

let me know if you have any questions, happy to help out if you get stuck

**Comment by daschl** [comment]
@uribro heyo, see my comment above - how do you want to tackle it? thanks!

**Comment by uribro** [comment]
Hi Michael,
I really want to contribute this code.
I don't know how to work with gerrit, so I tried to follow the manual and
stack a bit on (associated it with a SSH key).

Do you have some more info of how to do it?

**Comment by subalakr** [comment]
Hi @uribro,

I suppose you were able to register and sign the CLA  http://review.couchbase.org/#/settings/agreements. You can generate ssh key and add the public key here http://review.couchbase.org/#/settings/ssh-keys. On your .ssh config, you can add the host specific declarations like following

 Host review.couchbase.org
 Port            29418
 User            userid
 IdentityFile    ~/.ssh/id_rsa
 PreferredAuthentications publickey

**Comment by daschl** [comment]
@uribro does that help you further?

**Comment by subalakr** [comment]
@uribro can you sign the CLA here http://review.couchbase.org/#/settings/new-agreement with the email used in the patch uri.brodsky@gmail.com. Once you have signed it, we can upload the patch on your behalf to gerrit and get this merged. Thanks!

**Comment by subalakr** [comment]
Hi @uribro, since we didn't hear back from you. I went ahead and created the patch on gerrit with the changes. It is here http://review.couchbase.org/#/c/76437/. Thanks much for the contribution.

**Pull request closed without merging**
