### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Freddixx**
Fixed vars.

### CODE REVIEW

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

To get this change in and collaborate in code review, please register on Gerrit and accept our CLA.  More detailed instructions are available here: http://developer.couchbase.com/open-source-projects#how-to-contribute-code.

Note: Please contact us if you have any issues registering with Gerrit!  If you are not registered after 7 days, the Pull Request will automatically be closed.

::SDKBOT/PR:no_cla

**Comment by simonbasle** [comment]
@Freddixx I don't think you want to get set up on Gerrit just for a 1 word change. I'll do that myself and fix the README (through Gerrit, I don't get to avoid it). Thanks for the PR though!! :bow:

**Comment by simonbasle** [comment]
and actually the variable is correctly used, it's just that the name "`query`" is inadequate :sweat:

**Comment by simonbasle** [comment]
I'll do that as part of [JCBC-918](https://issues.couchbase.com/browse/JCBC-918) (i want to also get rid of the "Contributing" section in favor of linking to the far more complete `CONTRIBUTING.md`)

**Pull request closed without merging**
